# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

AdminUser:
  fields:
    default: email, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip
    form: email, reset_password_token, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip
  order_by: 
  relationships: 
  filters: created_at
  search: 
  application: photocollider

Contest:
  fields:
    default: name
    form: name
  order_by: 
  relationships: 
  filters: created_at
  search: name
  application: photocollider

Photo:
  fields:
    default: image_file_name, contest_id, user_id, contest, submitter
    form: image_file_name, contest_id, user_id, contest, submitter
  order_by: 
  relationships: contest, submitter
  filters: created_at
  search: 
  application: photocollider

User:
  fields:
    default: email, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip
    form: email, juror, reset_password_token, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip
  order_by: 
  relationships: 
  filters: created_at
  search: 
  application: photocollider

